# Generated by Django 5.0.4 on 2024-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0002_remove_braille_braille_braille_braille_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braille',
            name='binary',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='braille',
            name='category',
            field=models.CharField(blank=True, choices=[('abc', 'Alphabet'), ('123', 'Numbers'), ('!?.', 'Special Characters'), ('the', 'Combo Characters')], max_length=3, null=True),
        ),
    ]
