# Generated by Django 5.0.4 on 2024-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_app', '0003_alter_braille_binary_alter_braille_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrases',
            name='category',
            field=models.CharField(blank=True, choices=[('Sgn', 'Signs'), ('Dir', 'Directions'), ('Tim', 'Time')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='phrases',
            name='img',
            field=models.CharField(blank=True, null=True),
        ),
    ]
